package Compilador;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User_Len
 */
public class JForm1 extends javax.swing.JFrame {
    
    //Atributos, Objetos y Variables
    File ArchivoActual;
    ClaseJflex objFlex;
    ClaseCup objCup;

    /**
     * Creates new form JForm1
     */
    public JForm1() throws IOException, Exception {
        initComponents();
        String rutaJflex = "C:\\Users\\User_Len\\Documents\\GitHub\\AnalizadorLexico\\MINI_C\\Mini_C\\src\\Compilador\\Lexico.jflex";
        String rutaCUP = "C:\\Users\\User_Len\\Documents\\GitHub\\AnalizadorLexico\\MINI_C\\Mini_C\\src\\Compilador\\Sintactico.cup";
        //Crear clases de JFLEX
        jflex.Main.generate(new File(rutaJflex));
        //Crear clases del .CUP
        String[] cupCommands = {"-destdir", "C:\\Users\\User_Len\\Documents\\GitHub\\AnalizadorLexico\\MINI_C\\Mini_C\\src\\Compilador" ,"-parser", "ClaseCup", rutaCUP};
        java_cup.Main.main(cupCommands);
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnJflex = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbtnArchivo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jlbConsola = new javax.swing.JLabel();
        jlbTabla = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnJflex.setText("Análisis Léxico");
        jbtnJflex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJflexActionPerformed(evt);
            }
        });

        jButton2.setText("Análisis Sintáctico");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbtnArchivo.setText("Cargar Archivo");
        jbtnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnArchivoActionPerformed(evt);
            }
        });

        jButton1.setText("Análisis Semántico");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Valor", "Contexto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(jTextArea1);

        jlbConsola.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jlbConsola.setText("===Consola de Errores===");

        jlbTabla.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jlbTabla.setText("========Tabla de Simbolos========");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("MINI_C#");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnJflex)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbConsola)
                        .addGap(40, 40, 40)
                        .addComponent(jlbTabla)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnArchivo)
                    .addComponent(jbtnJflex)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbConsola)
                    .addComponent(jlbTabla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnJflexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJflexActionPerformed
            
        try {
            Reader Lector = new FileReader(ArchivoActual);
            objFlex = new ClaseJflex(Lector);
            objCup = new ClaseCup(objFlex);
            objCup.debug_parse();
            objCup.parse();
            jTextArea1.append(objFlex.lexicalError);
            System.out.print(objFlex.lexicalError);
            if(objCup.listOfErrors.equals("")){
                jTextArea1.append("\n" + "No hay errores sintácticos" + "\n");
            }
            else{
                jTextArea1.append(objCup.listOfErrors);
            }
            JOptionPane.showMessageDialog(null, "Ha concluido el análisis léxico.","Notificación",JOptionPane.OK_OPTION);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JForm1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(JForm1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnJflexActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser dialog = new JFileChooser();
     FileNameExtensionFilter filter = new FileNameExtensionFilter("archivos jcup", "cup");
     dialog.setFileFilter(filter);
     if(dialog.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) //Si se aprueba el archivo, generar clases del cup
     {
         File selectedFile = dialog.getSelectedFile();
         String route = selectedFile.getPath() ;
            try {
                
                java_cup.Main.main(new String[]{route}); //Generador del cup
            } catch (IOException ex) {
                Logger.getLogger(JForm1.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(JForm1.class.getName()).log(Level.SEVERE, null, ex);
            }
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnArchivoActionPerformed
        try{
            JFileChooser dialog = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("archivos frag", "frag");
            dialog.setFileFilter(filter);
            if(dialog.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
            {
                ArchivoActual = dialog.getSelectedFile();
                JOptionPane.showMessageDialog(null, "Se cargó el archivo exitosamente.","Notificación",JOptionPane.OK_OPTION);
            }
        }catch(Exception e){}
    }//GEN-LAST:event_jbtnArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JForm1().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(JForm1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtnArchivo;
    private javax.swing.JButton jbtnJflex;
    private javax.swing.JLabel jlbConsola;
    private javax.swing.JLabel jlbTabla;
    // End of variables declaration//GEN-END:variables
}
